version: '3'
services:
  vue-app1:					# Se declara un nuevo contenedor
    container_name: chavesdayron-tarea2-3031	# Se establece el nombre
    build: ./vue-project   			# El contenedor esta basado en el proyecto vue (utiliza su Dockerfile)
    environment:
      - PORT=5050				# Se abre y se le asigna el puerto 5050
    networks:
      - loadbalancing				# Se inserta este contenedor dentro de la red loadbalancing
  
  vue-app2:					# Se crea una replica del contenedor anterior
    container_name: chavesdayron-tarea2-3031-2	# (el estudiante esta al tanto de las palabras clave "deploy: mode: replicated replicas: 2")
    build: ./vue-project   
    environment:
      - PORT=5050 
    networks:
      - loadbalancing
      
  nginx:					# Se declara un nuevo contenedor
    container_name: nginx_balancer		# Se establece el nombre
    build: ./nginx  				# El contenedor esta basado en la carpeta nginx
    ports:
      - "80:80"					# Se abre y se le asigna el puerto 80
    networks:
      - loadbalancing				# Se inserta este contenedor dentro de la red loadbalancing
    depends_on:
      - vue-app1				# Se establecen sus dependencias para que sea el ultimo contenedor en crearse
      - vue-app2
      
networks:					# Se declara la red loadbalancing
  loadbalancing: